[build]
  command = "apt-get install -y --no-install-recommends openjdk-11-jdk && yarn --prod run clean && yarn --prod run html && yarn --prod run compile-css && yarn --prod run compile-js"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200